// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/meeting/[id]" | "/app/workspaces" | "/changelog" | "/invite/[id]" | "/link-device" | "/login" | "/pricing" | "/share/[token]"
type AppRouteHandlerRoutes = "/api/auth/[...all]" | "/api/billing/checkout" | "/api/billing/portal" | "/api/billing/status" | "/api/billing/webhook" | "/api/device/link" | "/api/sync/media" | "/api/sync/ping" | "/api/sync/pull" | "/api/sync/push" | "/api/sync/share" | "/updates/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...all]": { "all": string[]; }
  "/api/billing/checkout": {}
  "/api/billing/portal": {}
  "/api/billing/status": {}
  "/api/billing/webhook": {}
  "/api/device/link": {}
  "/api/sync/media": {}
  "/api/sync/ping": {}
  "/api/sync/pull": {}
  "/api/sync/push": {}
  "/api/sync/share": {}
  "/app": {}
  "/app/meeting/[id]": { "id": string; }
  "/app/workspaces": {}
  "/changelog": {}
  "/invite/[id]": { "id": string; }
  "/link-device": {}
  "/login": {}
  "/pricing": {}
  "/share/[token]": { "token": string; }
  "/updates/[...path]": { "path": string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
