// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/app/meeting/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/meeting/[id]">> = Specific
  const handler = {} as typeof import("../../../app/app/meeting/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/workspaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/workspaces">> = Specific
  const handler = {} as typeof import("../../../app/app/workspaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../../app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/invite/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[id]">> = Specific
  const handler = {} as typeof import("../../../app/invite/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/link-device/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/link-device">> = Specific
  const handler = {} as typeof import("../../../app/link-device/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/share/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[token]">> = Specific
  const handler = {} as typeof import("../../../app/share/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/status">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/device/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/device/link">> = Specific
  const handler = {} as typeof import("../../../app/api/device/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/media">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/ping">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/pull/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/pull">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/pull/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/push/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/push">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/push/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sync/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/share">> = Specific
  const handler = {} as typeof import("../../../app/api/sync/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/updates/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/updates/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/updates/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
